apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-pod-dev
  labels:
    app: nginx-pod-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: nginx-pod-dev
    name: in-cluster
  source:
    repoURL: git@github.com:nightmar39/argo-submodule.git
    targetRevision: main
    path: ./cd-five-mins/k8s-resources/nginx-pod/dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
